print("Welcome to the hypotenuse calculator for right triangles!")
print(" ")
print("               /|")
print("              / |")
print("             /  |")
print("     c ---> /   |")
print("           /    | <--- a")
print("          /     |")
print("         /      |")
print("        /_______|")
print("             ^   ")
print("             |   ")
print("             |   ")
print("             c   ")
print(" ")
a = float(input("please tell me the lenght of side a"))
b = float(input("please tell me the lenght of side b"))
print("the hypotenuse (c) =",(a*a + b*b)**.5)          
